### ISSUE TITLE
MFCC count regression in createMeydaAnalyzer

### ISSUE THREAD

**Issue by hughrawlinson** [meyda/meyda#300]
[From Slack](https://web-audio.slack.com/archives/C51A03LBS/p1558146955003300)
> Josh Ryan [10:35 PM]
> Hey Meyda! Thanks for creating this awesome package. I just wanted to note that your tutorial on real-time feature extraction in browser says that you can set the number of MFCC's to return in the createMeydaAnalyzer constructor, but it looks like you guys removed this capability in the last commit 5 days ago.

**Comment by hughrawlinson** [comment]
So it turns out this wasn't actually a regression. The mentioned tutorial never actually documented the parameter to the analyzer constructor because we never actually released a version of meyda with that change. Last week, I merged it and a fix to the ZCR extractor, before reverting the changes as I thought they were major breaking changes, and put them in the v5 branch. On further inspection though, I actually don't think they're breaking changes, so we should be good to merge to master and deploy a minor bump - `meyda@4.3.0`. Unless I get told not to by the other maintainers, I'll likely do so in the next few days. I'll keep this issue open until that happens.

**Comment by Fluxionsdx** [comment]
(Josh Ryan from Slack here). Sorry, it wasn't the tutorial, but rather the documentation on Features. From the MFCC description: "Range: An array of values representing the intensity for each Mel band. The default size of the array is 13, but is configureable via numberOfMFCCCoefficients"

**Comment by hughrawlinson** [comment]
Ah! I think that line in the docs refers to the value [on the Meyda object](https://github.com/meyda/meyda/blob/master/src/main.js#L124) directly, which is used in offline extraction, as opposed to the parameter to the MeydaAnalyzer factory, which hasn't yet been shipped. I think the best way to resolve this is to ship the extra param for the MeydaAnalyzer factory so that this will also be useful in Web Audio.

**Comment by syshen** [comment]
Hi, is there any way to set the numberOfMFCCCoefficients up to 64? I read the code, there is an upper bound limit which is 40. But I need to set it up to 64.

**Comment by miaobin** [comment]
Hi @hughrawlinson, I set the "numberOfMFCCCoefficients" to 26 but still get the result MFCC buffer which  size is 13. Did I understand wrong with this arg?

**Comment by hughrawlinson** [comment]
@nevosegal hey do you know why there's an upper bound to the number of mfccs, and the mel bank length?

**Comment by nevosegal** [comment]
There is no real reason that the max number of filters is set to 40. I thought it was standard when I implemented it but I since learned this isn't the case. We can add this functionality but we'll need to re-generate the filter bank when the value is modified.

@miaobin can you post an example? What version of Meyda are you using?

**Comment by miaobin** [comment]
@nevosegal I am now trying to implement DeepSpeech on browsers. I need to calculate the mfccs with 26 numbers of the input audio to feed the tensorflow model. So I use Meyda by pasting `<script src="https://unpkg.com/meyda/dist/web/meyda.min.js"></script>` into my HTML. Then I set `"numberOfMFCCCoefficients" : 26`. But I still get the array which length is 13.

**Comment by miaobin** [comment]
I read the code this morning and found that there is no construction information of "numberOfMFCCCoefficients" in [meyda-wa.js](https://github.com/meyda/meyda/blob/master/src/meyda-wa.js#L28). T tried to add 
`this._m.numberOfMFCCCoefficients = options.numberOfMFCCCoefficients || this._m.numberOfMFCCCoefficients || 13;` 
into the constructor and it works like the instruction:
`Range: An array of values representing the intensity for each Mel band. The default size of the array is 13, but is configureable via numberOfMFCCCoefficients.`

**Comment by hughrawlinson** [comment]
@miaobin @Fluxionsdx  this is fixed in meyda@4.3.0. Hope that helps, and sorry for not updating you earlier!
